drop table IF EXISTS DWS_XQ_JXL37JYY_TMP_1_1 purge;
CREATE TABLE DWS_XQ_JXL37JYY_TMP_1_1 as
SELECT *
FROM DWD.DWD_LCZHZHJXLCOUNT P
WHERE P.PAYINTV = '年缴'
    AND P.POLNO <> '21001012055'
    AND (
        (
            P.RISKTYPE <> '短险'
            AND P.SALECHNL IN ('02', '03')
        )
        OR P.SALECHNL NOT IN ('02', '03')
    )
    AND P.STATE NOT IN ('理赔终止', '特殊撤件保全')
    AND NOT EXISTS (
        SELECT 1
        FROM ODS.LCZHJXLPREMHM HM
        WHERE HM.FREEFLAG = '1'
            AND HM.CONTNO = P.CONTNO
            AND HM.FREESTARTDATE <= ADD_MONTHS(P.CVALIDATE, 36)
    );